import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Image from 'next/image';

import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Pudgy Pop Demo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Image
          className="-z-40"
          src="/bg.png"
          alt="Background"
          layout="fill"
          objectFit="cover"
          quality={100}
          priority
        />
        <div className="absolute inset-0 bg-gradient-to-b from-sky-400 to-blue-300 -z-50"></div>
        {children}
      </body>
    </html>
  );
}
