import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Pudgy Pop Demo',
  description: 'Generated by create next app',
};

const BackgroundSkyGradient = () => (
  <div className="absolute inset-0 bg-gradient-to-b from-sky-400 from-10% via-blue-300 via-30% to-indigo-50 to-70% -z-50"></div>
);

const BackgroundImageDiv = (props: { children: React.ReactNode }) => (
  <div className="bg-main min-h-dvh bg-[40%_-100px] md:bg-[50%_-150px] bg-[length:300%_100%] md:bg-cover bg-no-repeat">
    <BackgroundSkyGradient />
    {props.children}
  </div>
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="min-w-[375px] scroll-smooth" lang="en">
      <body className={`relative ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <BackgroundImageDiv>{children}</BackgroundImageDiv>
      </body>
    </html>
  );
}
