import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { BackgroundImage } from './_/background';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Pudgy Pop Demo',
  description: 'Generated by create next app',
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="min-w-[375px] scroll-smooth" lang="en">
      <body className={`relative ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <BackgroundImage>{children}</BackgroundImage>
      </body>
    </html>
  );
}
